// Class: ReadBDTMitFisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTMitFisher
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/02       [394754]
Creator        : atrisovi
Date           : Thu Feb 23 16:19:31 2017
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-573.8.1.el6.x86_64 #1 SMP Wed Nov 11 15:27:45 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /eos/lhcb/user/a/atrisovi/analysis-case-study/Step4_tmva
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
UseFisherCuts: "True" [Use multivariate splits using the Fisher criterion]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
D_DIRA_OWNPV                  D_dira                        D_dira                        D_dira                                                          'F'    [0.999900400639,1]
D_IPCHI2_OWNPV                D_ipchi                       D_ipchi                       D_ipchi                                                         'F'    [0.0015236166073,29.9032516479]
D_ENDVERTEX_CHI2              D_edchi                       D_edchi                       D_edchi                                                         'F'    [0.00525892199948,17.965221405]
piplus_PT                     pi_pt                         pi_pt                         pi_pt                                                           'F'    [300.603302002,12641.4570312]
log(piplus_IPCHI2_OWNPV)      pi_ipchi                      pi_ipchi                      pi_ipchi                                                        'F'    [1.7938605547,9.54668617249]
log(piplus_P)                 pi_p                          pi_p                          pi_p                                                            'F'    [7.61417961121,12.506357193]
max(muminus_P,muplus_P)       max_mu_p                      max_mu_p                      max_mu_p                                                        'F'    [3726.32617188,320239.0625]
min(muminus_P,muplus_P)       min_mu_p                      min_mu_p                      min_mu_p                                                        'F'    [3032.62329102,188784.84375]
max(muminus_PT,muplus_PT)     max_mu_pt                     max_mu_pt                     max_mu_pt                                                       'F'    [412.208679199,17817.3378906]
min(muminus_PT,muplus_PT)     min_mu_pt                     min_mu_pt                     min_mu_pt                                                       'F'    [402.438873291,6258.97851562]
log(D_TAU)                    D_tau                         D_tau                         D_tau                                                           'F'    [-9.12446498871,-2.72319579124]
log(min(muminus_IPCHI2_OWNPV,muplus_IPCHI2_OWNPV)) min_mu_ip                                          min_mu_ip                                          min_mu_ip                                                                                                 'F'    [1.79289484024,9.05229854584]
log(max(muminus_IPCHI2_OWNPV,muplus_IPCHI2_OWNPV)) max_mu_ip                                          max_mu_ip                                          max_mu_ip                                                                                                 'F'    [1.85593211651,10.7096033096]
D_PT                          D_pt                          D_pt                          D_pt                                                            'F'    [16.1055030823,23162.3046875]
log(D_FDCHI2_OWNPV)           D_fd                          D_fd                          D_fd                                                            'F'    [1.99363315105,13.5393600464]
D_P                           D_p                           D_p                           D_p                                                             'F'    [9893.37402344,544629.1875]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTMitFisherNode
   
#ifndef BDTMitFisherNode__def
#define BDTMitFisherNode__def
   
class BDTMitFisherNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTMitFisherNode ( BDTMitFisherNode* left,BDTMitFisherNode* right,
                          int nFisherCoeff,
                          double fisherCoeff0,
                          double fisherCoeff1,
                          double fisherCoeff2,
                          double fisherCoeff3,
                          double fisherCoeff4,
                          double fisherCoeff5,
                          double fisherCoeff6,
                          double fisherCoeff7,
                          double fisherCoeff8,
                          double fisherCoeff9,
                          double fisherCoeff10,
                          double fisherCoeff11,
                          double fisherCoeff12,
                          double fisherCoeff13,
                          double fisherCoeff14,
                          double fisherCoeff15,
                          double fisherCoeff16,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fNFisherCoeff ( nFisherCoeff ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
     fFisherCoeff.push_back(fisherCoeff0);
     fFisherCoeff.push_back(fisherCoeff1);
     fFisherCoeff.push_back(fisherCoeff2);
     fFisherCoeff.push_back(fisherCoeff3);
     fFisherCoeff.push_back(fisherCoeff4);
     fFisherCoeff.push_back(fisherCoeff5);
     fFisherCoeff.push_back(fisherCoeff6);
     fFisherCoeff.push_back(fisherCoeff7);
     fFisherCoeff.push_back(fisherCoeff8);
     fFisherCoeff.push_back(fisherCoeff9);
     fFisherCoeff.push_back(fisherCoeff10);
     fFisherCoeff.push_back(fisherCoeff11);
     fFisherCoeff.push_back(fisherCoeff12);
     fFisherCoeff.push_back(fisherCoeff13);
     fFisherCoeff.push_back(fisherCoeff14);
     fFisherCoeff.push_back(fisherCoeff15);
     fFisherCoeff.push_back(fisherCoeff16);
   }

   virtual ~BDTMitFisherNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTMitFisherNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTMitFisherNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTMitFisherNode*   fLeft;     // pointer to the left daughter node
   BDTMitFisherNode*   fRight;    // pointer to the right daughter node
   int                     fNFisherCoeff; // =0 if this node doesn use fisher, else =nvar+1 
   std::vector<double>     fFisherCoeff;  // the fisher coeff (offset at the last element)
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTMitFisherNode::~BDTMitFisherNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTMitFisherNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
   if (fNFisherCoeff == 0){
     result = (inputValues[fSelector] > fCutValue );
   }else{
     double fisher = fFisherCoeff.at(fFisherCoeff.size()-1);
     for (unsigned int ivar=0; ivar<fFisherCoeff.size()-1; ivar++)
       fisher += fFisherCoeff.at(ivar)*inputValues.at(ivar);
     result = fisher > fCutValue;
   }
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTMitFisherNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTMitFisher : public IClassifierReader {

 public:

   // constructor
   ReadBDTMitFisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTMitFisher" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "D_DIRA_OWNPV", "D_IPCHI2_OWNPV", "D_ENDVERTEX_CHI2", "piplus_PT", "log(piplus_IPCHI2_OWNPV)", "log(piplus_P)", "max(muminus_P,muplus_P)", "min(muminus_P,muplus_P)", "max(muminus_PT,muplus_PT)", "min(muminus_PT,muplus_PT)", "log(D_TAU)", "log(min(muminus_IPCHI2_OWNPV,muplus_IPCHI2_OWNPV))", "log(max(muminus_IPCHI2_OWNPV,muplus_IPCHI2_OWNPV))", "D_PT", "log(D_FDCHI2_OWNPV)", "D_P" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTMitFisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTMitFisherNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTMitFisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTMitFisherNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTMitFisherNode*)current->GetRight();
         else current=(BDTMitFisherNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDTMitFisher::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.644565306333121);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 5.63134, 1, 1, 0.808706,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.566176,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.0625,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.46184e-09, -2.4353e-06, -0.000180177, 0, 0.293845, 0, 0.232892, 0.000113659, -0.241741, -9.6381e-07, 2.51722, 16, -0.0960563, 0, 0, 0.37963,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.91296, 0, 0, 0.7236,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.535948,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.263598,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999969, 0, 0, 0.369898,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 4.73107e-06, 0, -0.000344343, 0, 0.369688, 0, 0, 0.000264974, -0.183875, -4.69434e-06, 3.67772, -1, 0.00980905, 0, -1, 0.129094,-99) , 
17, 0, 0, 0, 0, 0, 0, 2.61763e-06, 0, -0.000199393, 0, 0.436376, 0, 0.0617329, 0.00014431, -0.227692, -4.00125e-06, 4.15727, 16, -0.00468141, 0, 0, 0.232711,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999986, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.490594);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.855684,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.432217,-99) , 
17, 0, 0, 0, 0, 0, 0, 2.96844e-06, 9.42406e-06, -0.000114071, 0, 0.174988, 0, 0.11119, 0.000100639, -0.0602889, -4.50798e-06, 0.894088, 16, -0.182062, 0, 0, 0.774612,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.537358,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.264422,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 49852, 1, 0, 0.395056,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4.99358, 1, 0, 0.705946,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.555095,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.26269,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 7.14408, 1, 0, 0.440651,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 556.204, 1, -1, 0.138943,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.72089, 0, 0, 0.34162,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999995, 0, 0, 0.469336,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.371241);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.87432, 0, 1, 0.754997,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.572373,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.350589,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 5.53218, 0, 0, 0.443934,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3.74557, 1, 0, 0.668053,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.504801,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.165198,-99) , 
17, 0, 0, 0, 0, 0, 0, -2.97162e-06, 0, -0.000140983, 0, 0.0291982, 0, 0.0424217, 9.3244e-05, -0.0623929, -6.8491e-07, 0.438701, 16, -0.147682, 0, 0, 0.463703,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.513881,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.184501,-99) , 
17, 0, 0, 0, 0, 0, 0, 3.01585e-06, 0, -0.000173301, 4.32016e-05, 0.322949, 0, 0.0795631, 0.000110615, -0.145538, -2.102e-06, 2.70632, 16, 0.151509, 0, 0, 0.226167,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5.11138, 1, 0, 0.348742,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999995, 0, 0, 0.458,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.355335);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
17, 0, 0, 0, -0.000679741, 0, 0.0511634, -4.91194e-06, -9.48773e-06, -0.000553253, -0.000198874, 0.179742, -0.00359776, -0.014385, 0.000567727, -0.0130124, 1.32122e-06, 1.12943, -1, 0.131252, 0, 1, 0.835847,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.598674,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.290128,-99) , 
17, 0, 0, 0, 0, 0, 0, 4.43776e-07, 0, -0.000112507, 0, -0.0690752, 0, 0.0456856, 4.83656e-05, -0.0200841, -1.79232e-06, -0.397079, 16, -0.0795184, 0, 0, 0.527298,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.615146,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.02991, 0, -1, 0.336591,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999995, 0, 0, 0.430449,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.339049);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 6.83986, 1, 1, 0.697031,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.531559,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.238634,-99) , 
17, 0, 0, 0, 0, -0.0514949, 0, -5.39112e-07, 2.21576e-06, 5.7441e-06, 0, -0.141948, 0, -0.10253, -3.29378e-05, 0.193669, -7.81533e-07, -1.26941, 16, -0.0258714, 0, 0, 0.432501,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 5.69709, 1, 0, 0.591966,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.523435,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.219465,-99) , 
17, 0, 0, 0, 0, 0, 0, -5.90141e-06, 0, 0, 0, 0.0591067, 0, -0.219623, 0, 0.229009, 2.67313e-06, 0.204884, 16, -0.0662966, 0, 0, 0.427667,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 4.80027e-06, -8.06634e-06, -0.00049338, 0, 0.423016, 0, 0, 0.00042149, -0.233538, -3.81305e-06, 4.28702, -1, -0.105705, 0, -1, 0.173302,-99) , 
17, 0, 0, 0, 0, 0, 0, -2.70998e-06, 0, -9.45498e-05, 0, 0.177441, 0, 0.0960692, 7.68664e-05, -0.144989, 8.30046e-07, 1.59138, 16, -0.0727348, 0, 0, 0.359162,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4.00895, 0, 0, 0.466937,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.320825);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.743912,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.47466,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6.85951, 1, 0, 0.669497,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.500741,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.293847,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 13.1558, 1, 0, 0.446971,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2.84931, 1, 0, 0.53232,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.738296,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.378906,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.28061e-06, 0, -0.000240579, 0, 0.150099, 0, 0.0738633, 0.000166504, -0.131568, 6.74638e-07, 1.39041, 16, 0.0807997, 0, 0, 0.480957,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 13740, 0, -1, 0.27389,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3.4262, 1, 0, 0.350853,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4.00895, 0, 0, 0.434896,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.262062);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.594432,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.410787,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6.83986, 1, 0, 0.538033,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, -7.61912e-06, -1.11087e-05, 1.19468e-05, 0, -0.105648, 0, -0.495591, -6.88537e-05, 0.565088, 8.08121e-06, -1.327, -1, -0.000863397, 0, -1, 0.360126,-99) , 
17, 0, 0, 0, 0, 0, 0, -3.786e-07, 0, -3.61793e-05, 0, 0.0135871, 0, -0.0801829, 9.314e-06, 0.0805588, 4.58816e-07, 0.0223598, 16, -0.0330006, 0, 0, 0.474745,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0.129318, 0, 4.95121e-05, 0, -0.000784719, 0, 0.216252, -0.224, 0.187602, 0.000637908, -0.168384, -4.09111e-05, 2.33053, -1, -0.0191258, 0, -1, 0.178129,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.59415e-06, 0, -6.65209e-05, 0, 0.0505545, 0, 0.0315695, 4.22636e-05, -0.0340485, -6.70898e-07, 0.374895, 16, -0.0742627, 0, 0, 0.448833,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.204211);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.554383,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.397552,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 5.69709, 1, 0, 0.497058,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.74422, 1, -1, 0.269831,-99) , 
17, 0, 0, 0, 0, 0, 0, -3.6594e-07, 0, -1.73416e-05, 0, 0.0151044, 0, -0.0447612, 1.09343e-05, 0.0472896, 2.50647e-07, 0.0288066, 16, -0.0471157, 0, 0, 0.475047,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.00822177,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.05451e-06, 0, -3.91861e-05, 0, 0.00992781, 0, 0.0367147, 2.79053e-05, -0.0274881, -4.69435e-07, 0.0292667, 16, -0.0998636, 0, 0, 0.459546,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.200922);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.673123,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.459954,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2.84931, 1, 0, 0.536708,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 10.6914, 1, -1, 0.416622,-99) , 
17, 0, 0, 0, 0, 0, 0, -7.34435e-07, 0, -2.53333e-08, 0, -0.0106894, 0, -0.057293, -3.93804e-06, 0.0726, 5.97543e-07, -0.230682, 16, -0.00678282, 0, 0, 0.469811,-99) , 
NN(
0, 
0, 
17, 15210.8, 0.0261275, 0, 0, 0, 0, 2.67657e-05, 2.13344e-05, -0.00117885, 0, 0.637615, 0.350551, 0.0624207, 0.000949453, -0.499317, -1.56717e-05, -15204.3, -1, -0.59754, 0, -1, 0.161791,-99) , 
17, 0, 0, 0, 0, 0, 0, 9.69039e-07, 0, -2.85465e-05, 0, 0.00375872, 0, 0.0361446, 2.09741e-05, -0.021607, -2.87859e-07, -0.0520336, 16, -0.0739775, 0, 0, 0.453091,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.124296);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.531069,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.390433,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 14.2404, 1, 0, 0.515462,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.29312,-99) , 
17, 0, 0, 0, 0, 0, 0, -5.90087e-07, 0, 9.48149e-07, 0, -0.00299933, 0, -0.0367978, -2.34318e-06, 0.0473598, 4.86118e-07, -0.130824, 16, -0.0388349, 0, 0, 0.503403,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.190865,-99) , 
17, 0, 0, 0, 0, 0, 0, 8.47191e-07, 0, -2.31739e-05, 0, -0.00313157, 0, 0.041712, 1.71444e-05, -0.0262314, -2.07486e-07, -0.0967219, 16, -0.0844525, 0, 0, 0.48781,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.151314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.523169,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.393025,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8.54602, 0, 0, 0.506844,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 3.96589e-06, -2.27379e-06, -8.30326e-05, 0, 0.241985, 0, -0.656691, 5.16116e-05, 0.577191, -2.70198e-06, 1.89619, -1, -0.0695799, 0, -1, 0.325673,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.20722e-06, 0, 1.26718e-05, 0, -0.0138077, 0, -0.0625825, -1.41639e-05, 0.0702854, 7.24434e-07, -0.18711, 16, -0.0371214, 0, 0, 0.491109,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.654501,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, -0.167083, 0, 0, -0.000323102, 0, 0.296451, 0.123919, 0.0945822, 0.000308058, -0.198367, 7.05095e-06, 3.73568, -1, -0.117272, 0, -1, 0.132851,-99) , 
17, 0, 0, 0, 0, 0, 0, 2.79782e-05, 1.90553e-05, -0.000447968, 0, 0.142215, 0, 0, 0.000288274, -0.088068, -9.82498e-06, 1.17767, 16, 0.108491, 0, 0, 0.299397,-99) , 
17, 0, 0, 0, 0, 0, 0, 8.06066e-07, 0, -1.99963e-05, 0, -0.00956342, 0, 0.0358637, 1.40788e-05, -0.0180724, -1.52348e-07, -0.160249, 16, -0.0427999, 0, 0, 0.469023,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.207804);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.79927, 1, 1, 0.570294,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.52181, 1, -1, 0.434132,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.2691e-06, 0, 3.13066e-05, 0, -0.0301696, 0, -0.0433547, -2.59756e-05, 0.0729559, 7.60432e-07, -0.414292, 16, 0.0156026, 0, 0, 0.473905,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.697277,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 736.633, 1, -1, 0.177866,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 522.165, 1, 0, 0.325659,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 1118.31, 0, 0, 0.450078,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.215575);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.566204,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.45848,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 11878, 1, 0, 0.521058,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.678091,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.34501,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 13.9335, 0, 0, 0.410408,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 8.55762, 1, 0, 0.495364,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.651709,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 736.633, 1, -1, 0.210308,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 522.165, 1, 0, 0.338374,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 1118.31, 0, 0, 0.471115,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.176795);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 1, 0.538985,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.600245,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.416281,-99) , 
17, 0, 0, 0, 0, 0, 0, -2.57116e-06, 0, -2.42891e-05, 0, 0.0407316, 0, -0.0799318, 8.17175e-06, 0.0533723, 1.16973e-06, 0.389189, 16, 0.0307616, 0, 0, 0.460416,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999991, 0, 0, 0.495496,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.594962,-99) , 
NN(
0, 
0, 
17, 5957.96, 0, 0, 0, 0, -0.306122, -1.55627e-05, 0, -0.000368955, -0.0012151, 0.233009, 0.148476, -0.00774597, 0.000424278, -0.227747, 1.08589e-05, -5951.93, -1, -0.153021, 0, -1, 0.0943099,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.44625e-05, 0.000103971, -0.000190911, -0.00126342, -0.241992, 0.0698857, 0.0596294, 0.000265741, 0.0656569, -2.48981e-05, -2.24054, 16, 0.0732479, 0, 0, 0.279193,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.58797e-06, 0, -2.99903e-05, 0, 0.0472289, 0, 0.0442191, 2.62894e-05, -0.0636872, -4.27536e-07, 0.444186, 16, -0.0577374, 0, 0, 0.474782,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.199085);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.618568,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.402249,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 2.12149, 0, 0, 0.544467,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.549333,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.421324,-99) , 
17, 0, 0, 0, 0, 0, 0, 2.76814e-07, 0, -2.6959e-06, 0, 0.0970961, 0, 0.0209137, 1.13888e-05, -0.0463741, -4.47447e-07, 0.828078, 16, 0.0122382, 0, 0, 0.465341,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 2.77976, 1, 0, 0.486785,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.597655,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, -0.00091717, 0, -0.310773, -4.21842e-05, 0, -0.000408636, -0.000559625, 0.168084, 0.163178, 0.0707597, 0.000462383, -0.248767, 3.52128e-05, 5.2353, -1, -0.224706, 0, -1, 0.0885645,-99) , 
17, 0, 0, 0, -0.00108343, 0, 0, -8.21467e-06, 0, -0.000756028, -0.000772842, -0.0362065, 0.0354185, 0.00165998, 0.000682529, 0.023461, 1.16159e-05, 0.174667, 16, 0.043254, 0, 0, 0.27419,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.48808e-06, 0, -1.97189e-05, 0, 0.0295368, 0, 0.0508808, 1.86247e-05, -0.0658253, -6.3732e-07, 0.324336, 16, -0.0679234, 0, 0, 0.469089,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.102274);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.510916,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.2883,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999919, 0, 0, 0.502639,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.290326,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 3.73805, 0, 0, 0.49553,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.639442,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, -0.000840275, 0, 0, -1.54935e-05, 6.51857e-05, -0.000359332, -0.000996566, 0.111857, 0.0720009, 0.0621397, 0.000481679, -0.123921, 5.91564e-06, 1.64996, -1, -0.0806117, 0, -1, 0.109326,-99) , 
17, 0, 0, 0, -0.000992228, 0, 0, -2.15361e-06, 5.19559e-05, -0.000574157, -0.00131416, -0.125189, 0.0400526, 0.0569403, 0.000619676, 0.0136613, 3.62743e-07, -0.518369, 16, 0.0628035, 0, 0, 0.288005,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.08993e-06, 0, -1.72736e-05, 0, -0.0229768, 0, 0.0429265, 1.40693e-05, -0.0407438, -3.2768e-07, -0.151165, 16, -0.0597245, 0, 0, 0.476215,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.210454);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.554212,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.397102,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 13740, 0, 0, 0.509693,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.576254,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.386998,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 36331.2, 1, 0, 0.43649,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3.76054, 1, 0, 0.47242,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.617964,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, -0.00103074, 0, 0, -2.01257e-05, 7.84181e-05, -0.000474188, -0.0012929, 0.0351787, 0.0678263, 0.0565513, 0.000600819, -0.0743911, 8.89166e-06, 1.03748, -1, -0.0851432, 0, -1, 0.134131,-99) , 
17, 0, 0, 0, -0.000924535, 0, 0, -2.08579e-06, 4.31974e-05, -0.000553243, -0.0011559, -0.0936919, 0.0270107, 0.0657845, 0.000590575, -0.00788, 8.4017e-07, -0.231313, 16, 0.074665, 0, 0, 0.300681,-99) , 
17, 0, 0, 0, 0, 0, 0, 9.99256e-07, 0, -1.63748e-05, 0, -0.0223707, 0, 0.0373461, 1.28625e-05, -0.0371232, -3.08661e-07, -0.137654, 16, -0.0554741, 0, 0, 0.456813,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0841355);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0.999919, 0, -1, 0.476514,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.514027,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.191033,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 5.98421, 0, 0, 0.336276,-99) , 
17, 0, 0, 0, 0, 0, 0, 9.90766e-08, 0, -6.45483e-06, 0, 0.00240865, 0, -0.00357738, 8.82407e-06, 0.00158406, 7.55287e-08, -0.00230657, 16, -0.0222987, 0, 0, 0.467216,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.1982,-99) , 
17, 0, 0, 0, 0, 0, 0, 9.75984e-07, 0, -2.03303e-05, 0, -0.00820352, 0, 0.0321558, 1.83359e-05, -0.0314293, -3.35061e-07, -0.0591751, 16, -0.0872071, 0, 0, 0.458842,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.106757);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.567379,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.475452,-99) , 
17, 0, 0, 0, 0, 0, 0, -3.17036e-07, 0, 2.70982e-06, 0, -0.0344725, 0, -0.0299027, -3.37386e-06, 0.0441668, 2.97651e-07, -0.361, 16, 0.00976152, 0, 0, 0.498933,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.250296,-99) , 
17, 0, 0, 0, 0, 0, 0, 6.72627e-07, 0, -1.44097e-05, 0, 0.0138144, 0, 0.018499, 1.59622e-05, -0.0161477, -2.64559e-07, 0.0686477, 16, -0.0434603, 0, 0, 0.487032,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.216465,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, -5.4666, 1, 0, 0.478573,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.124352);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.568417,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.446898,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 4.84398, 1, 0, 0.542243,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 1.20739e-06, 0, -1.33584e-05, 0, 0.164489, -0.0552388, -0.0270115, 2.25078e-05, 0.000160525, -5.70848e-07, 1.44533, -1, -0.0723262, 0, -1, 0.476644,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 4.28144, 1, 0, 0.509019,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.613267,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.370126,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 9979.33, 0, 0, 0.494423,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.0861525,-99) , 
17, 0, 0, 0, -0.000754325, 0, 0.0886148, 6.94173e-06, 0, -0.000633716, -0.000377092, 0.162095, 0.0405857, 0.0284503, 0.000518884, -0.081036, 1.37384e-06, 0.973453, 16, -0.0817551, 0, 0, 0.330626,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.20137e-06, 0, -2.30537e-05, 0, 0.00935508, 0, 0.0428266, 1.94052e-05, -0.05025, -5.31343e-07, 0.132332, 16, -0.0533073, 0, 0, 0.492631,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.117778);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.544677,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.468572,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1477.86, 1, 0, 0.522286,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.37988,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 3.94228, 0, 0, 0.515012,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.54865,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.182646,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 33829.1, 0, 0, 0.36508,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.04923e-06, 0, -2.43274e-05, 0, 0.0135411, 0, 0.0441263, 2.09334e-05, -0.0492074, -5.04751e-07, 0.147639, 16, -0.0463204, 0, 0, 0.500097,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.100641);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.781103,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.431505,-99) , 
17, 0, 0, 0, 0, 0, 0, -6.89078e-07, 0, -5.48479e-05, 0, 0.749881, -0.127501, -0.100831, 0.000117434, -0.211546, 8.50739e-07, 7.19621, 16, -0.0255059, 0, 0, 0.635539,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.511539,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.375825,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 9.1574, 1, 0, 0.493621,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12.8338, 0, 0, 0.50353,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.531264,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.0172567,-99) , 
17, 0, 0, 0, 0, 0, 0, 5.61456e-06, 7.14425e-05, -0.000468057, -0.00133468, 0.304385, 0.106119, 0.00676123, 0.000473089, -0.194778, -1.00764e-05, 3.18223, 16, -0.213134, 0, 0, 0.317379,-99) , 
17, 0, 0, 0, 0, 0, 0, 7.50211e-07, 0, -3.49759e-05, 0, 0.0102972, 0, 0.0374223, 2.99945e-05, -0.043323, -3.78056e-07, 0.110983, 16, -0.0616715, 0, 0, 0.491053,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0873528);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.640718,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.480389,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12.8338, 0, 0, 0.491361,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.254772,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.13613e-07, 0, -2.03285e-05, 0, 0.0191279, 0, 0.00741313, 2.01898e-05, -0.0163014, -1.36036e-08, 0.16474, 16, -0.0326277, 0, 0, 0.483499,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.252848,-99) , 
17, 0, 0, 0, 0, 0, 0, 6.34341e-07, 0, -3.43566e-05, 0, 0.00509288, 0, 0.0355815, 2.94597e-05, -0.0396653, -3.51274e-07, 0.063747, 16, -0.0863307, 0, 0, 0.474312,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.147414);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.548886,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.426856,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 9.96877, 1, 0, 0.526662,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.521352,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.246974,-99) , 
17, 0, 0, 0, 0, 0, 0, 9.0884e-06, 0, -0.000245363, 0, 0.408377, 0, 0, 0.000221213, -0.176563, -2.10713e-06, 3.65133, 16, -0.040202, 0, 0, 0.399092,-99) , 
17, 0, 0, 0, 0, 0, 0, 5.1846e-07, 0, -2.99156e-05, 0, 0.0312954, 0, 0.0262467, 2.74079e-05, -0.0298311, -3.82805e-07, 0.235399, 16, -0.0266746, 0, 0, 0.500703,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.247882,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, -5.4666, 1, 0, 0.493338,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.256783);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.613787,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.386117,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 9.97346, 1, 0, 0.55595,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.541807,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.373567,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3.50864, 1, 0, 0.469557,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, -6.8258, 0, 0, 0.502836,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.368047,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 495.148, 1, 0, 0.735848,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 1.48426e-05, 1.0476e-05, -9.51224e-05, 0, 0.282638, -0.000309915, 0.0543801, 0.000119275, -0.183238, -1.083e-05, 2.68683, -1, -0.00945327, 0, -1, 0.337857,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 524.461, 1, 0, 0.415959,-99) , 
17, 0, 0, 0, 0, 0, 0, 4.72417e-07, 0, -2.93566e-05, 0, 0.00468113, 0, 0.033121, 2.46369e-05, -0.0324911, -2.46261e-07, 0.0345173, 16, -0.0139737, 0, 0, 0.475266,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.09186);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.512049,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.266318,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999919, 0, 0, 0.504024,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 6567.5, 1, -1, 0.309896,-99) , 
17, 0, 0, 0, 0, 0, 0, -7.32088e-07, 0, -1.53334e-05, 0, 0.00361315, 0, -0.0036166, 1.79468e-05, -0.00212024, 4.89081e-07, 0.0119491, 16, -0.0388137, 0, 0, 0.491323,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.561247,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.270271,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 9.45034, 1, 0, 0.432427,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.168063,-99) , 
17, 0, 0, 0, 0, 0, 0, 3.49703e-06, -6.43698e-06, 0, 0, 0.0145615, 0, 0.0774611, 0, -0.11617, -1.89602e-06, 0.47648, 16, -0.0259555, 0, 0, 0.345599,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.16304, 0, 0, 0.478158,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.26697);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.619909,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.410423,-99) , 
17, 0, 0, 0, 0, -0.0466383, 0, 3.22769e-06, 0, -4.23626e-05, 0, -0.0870391, -0.0370214, -0.103793, 1.00037e-05, 0.163055, -7.3351e-07, -0.771197, 16, -0.00850776, 0, 0, 0.527115,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.398445,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 498.272, 1, 0, 0.44736,-99) , 
17, 0, 0, 0, 0, 0, 0, -7.36255e-07, 0, -1.30104e-05, 0, 0.00445062, 0, -0.00271644, 1.54506e-05, -0.00223976, 4.82048e-07, 0.018965, 16, 0.00678406, 0, 0, 0.472701,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.541581,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.26827,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 9.45034, 1, 0, 0.416534,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.183322,-99) , 
17, 0, 0, 0, 0, 0, 0, 3.04887e-06, -6.38175e-06, 0, 0, 0.0215373, 0, 0.0751764, 0, -0.115746, -1.53934e-06, 0.525035, 16, -0.0317055, 0, 0, 0.348587,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.16304, 0, 0, 0.461649,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.113312);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.894742,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.434103,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 6.09215, 1, 0, 0.611229,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.513142,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.263197,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.23316, 1, 0, 0.496226,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.59544, 0, 0, 0.508484,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.538018,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.31935,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.02367, 0, 0, 0.429055,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.233389,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5.50091, 1, 0, 0.356963,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.16304, 0, 0, 0.495187,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.114346);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.884072,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.609701,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.34905,-99) , 
17, 0, 0, 0, -0.000321197, 0, 0, 7.15761e-06, -7.59802e-06, -0.000438116, -1.74308e-05, 0, 0, -0.00489437, 0.000307677, -0.0095995, -4.60355e-08, 0.194303, 16, 0.028454, 0, 0, 0.464562,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 6.09215, 1, 0, 0.622062,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 5.23316, 1, -1, 0.461172,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.59544, 0, 0, 0.476641,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.139762);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.676825,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.494458,-99) , 
17, 0, 0, 0, -3.75885e-05, 0, 0, 2.02837e-06, 0, -0.000173895, 0, 0, 0, -0.0165372, 5.06539e-05, 0.0145238, 1.61188e-07, 0.122505, 16, 0.00186255, 0, 0, 0.600942,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.650759,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.225787,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 964.998, 0, 0, 0.401985,-99) , 
17, 0, 0, 0, 0, 0, 0, 5.77014e-06, 0, -6.87358e-05, 0, -0.0429951, 0, -0.0424501, 1.22233e-05, 0.0263892, -1.7913e-06, -0.137296, 16, -0.0380926, 0, 0, 0.560132,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.511234,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.332583,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.97752e-06, 0, -1.54248e-05, 0, 0.0530447, 0, 0, 3.16722e-05, -0.0227431, 8.63027e-07, 0.446223, 16, -0.039526, 0, 0, 0.486856,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.260258,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2427.77, 1, 0, 0.475702,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.62984e-08, 0, -8.86622e-06, 0, 0.0279523, 0, 0.0187094, 1.21404e-05, -0.0184202, -2.44049e-07, 0.201225, 16, 0.0118673, 0, 0, 0.501626,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.174085);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.867031,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.592989,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.343185,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5.15664, 1, 0, 0.463547,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 6.09215, 1, 0, 0.612123,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.612872,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.447645,-99) , 
17, 0, 0, 0, 0, 0, 0, 2.75983e-08, 0, -1.71301e-05, 0, 0.0626294, 0, 0.0276022, 2.1544e-05, -0.0302025, -4.63779e-07, 0.473004, 16, 0.0277593, 0, 0, 0.48262,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.305925,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.23316, 1, 0, 0.471878,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.59544, 0, 0, 0.484906,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.139549);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, -1.82302e-06, 0, 9.94642e-06, 0, 0.0200382, 0, -0.0238976, 9.55982e-06, 0.00278695, 1.04482e-06, 0.185727, -1, 0.0376095, 0, 1, 0.533475,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.652343,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.249385,-99) , 
17, 0, 0, 0, 0, 0.0132192, 0, 8.6301e-06, 1.68927e-06, -0.00018244, 0, -0.0526093, -0.00143338, 0.229353, 0.000116207, -0.127204, -3.83283e-06, -1.15579, 16, -0.0213603, 0, 0, 0.425118,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2497.35, 1, 0, 0.521761,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.663983,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 1.18901e-05, 0, -0.000272369, 0, -0.0708933, 0, 0.0900305, 0.000140564, -0.00596041, -9.25012e-06, -0.657167, -1, -0.0994672, 0, -1, 0.352298,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 575.013, 1, 0, 0.43716,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.53222, 0, 0, 0.507344,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0957163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.828411,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.517591,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.358735,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5.15664, 1, 0, 0.435827,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 6.09215, 1, 0, 0.573356,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.591826,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.478177,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12.8338, 0, 0, 0.485773,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.32032,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.23316, 1, 0, 0.475722,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5.59544, 0, 0, 0.484526,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0826392);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.554637,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.495417,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999991, 0, 0, 0.52171,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.507213,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.151006,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.27129e-06, 6.97715e-06, 0, 0, 0.104527, 0, -1.68295, 0, 1.68234, -5.61168e-06, 0.370061, 16, -0.0410472, 0, 0, 0.34754,-99) , 
17, 0, 0, 0, 0, 0, 0, -5.77589e-07, 0, 8.47468e-06, 0, 0.00469674, 0, -0.0304151, -3.60163e-06, 0.0291017, 2.74975e-07, 0.00570995, 16, -0.0212434, 0, 0, 0.50781,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.321515,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.80009e-07, 0, -3.96814e-06, 0, -0.00394348, 0, 0.00504563, 5.7915e-06, -0.00432213, -9.07107e-08, -0.0394783, 16, -0.020485, 0, 0, 0.502848,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.189895);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.58485,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.403922,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 618.524, 0, 0, 0.451994,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 495.015, 1, 0, 0.541245,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.664521,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.49902,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 6.07664, 0, 0, 0.518816,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 1.2266e-05, 9.5431e-06, -0.000532437, -0.000378366, -0.0632439, 0, 0.105896, 0.000363494, -0.0732227, -9.53469e-06, -0.197878, -1, 0.00178839, 0, -1, 0.353848,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.22295e-06, -1.2052e-06, -2.78656e-05, 0, -0.0627154, 0, -0.009356, 2.99866e-05, 0.025691, -7.84545e-07, -0.591857, 16, -0.0457629, 0, 0, 0.480957,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 681.322, 1, 0, 0.505322,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.117446);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.67929, 1, 1, 0.546352,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.608869,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.287948,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3.83307, 1, 0, 0.451304,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 2.098, 0, 0, 0.538142,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.356404,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, -5.4666, 1, 0, 0.533306,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.108615);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.738027,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.492116,-99) , 
17, 0, 0, 0, 0, 0.0853808, 0, 3.93548e-06, 0, -7.96533e-05, 0, -0.507665, 0, 0.0158439, -1.00554e-05, 0.169279, 2.35152e-07, -4.96827, 16, 0.00442456, 0, 0, 0.639114,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.527144,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.456297,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 960.205, 1, 0, 0.505406,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.90612e-07, 0, 4.59316e-06, 0, -0.00727162, 0, -0.0055015, 1.64828e-06, 0.0003985, -4.3534e-08, -0.0315217, 16, 0.0224292, 0, 0, 0.515031,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.632428,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.0869954,-99) , 
17, 0, 0, 0, 0, 0.0535557, 0, -0.000320817, -0.000363024, -0.000378209, -0.000439, -0.403644, 0, -0.00411943, 0.000289475, 0.101063, 0.000318701, -3.93871, 16, -0.10245, 0, 0, 0.409265,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8.31306, 0, 0, 0.508016,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0761643);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.522356,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.336748,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999919, 0, 0, 0.516064,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 5.4817, 1, -1, 0.416479,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2.31898, 0, 0, 0.503663,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.372875,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 7.33159, 1, 0, 0.49824,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.1881);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.41179, 1, 1, 0.619639,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.400289,-99) , 
17, 0, 0, 0, 0, 0, 0, 9.50805e-07, 5.41174e-07, 0, 0, -0.205123, 0.0140642, 0.0345787, 0, 0.0652536, -9.62896e-07, -2.10639, 16, -0.0235295, 0, 0, 0.55428,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.434756,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 496.17, 1, 0, 0.688881,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, 1.5187e-06, 0, -4.70301e-05, 0, 0.0864924, 0, 0.00291989, 5.10513e-05, -0.0472836, -8.46019e-07, 0.802125, -1, -0.0523624, 0, -1, 0.438771,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 525.564, 1, 0, 0.473695,-99) , 
17, 0, 0, 0, 0, 0, 0, 3.40495e-07, 0, -6.8193e-06, 0, -0.0146673, 0, 0.00600563, 9.32627e-06, -0.00659525, -2.14923e-07, -0.10944, 16, 0.0191201, 0, 0, 0.486374,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.155552);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 5801.19, 1, 1, 0.556254,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.640245,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.289576,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.71053e-06, -3.22472e-07, -0.000536421, -0.000698181, 0.21048, 0, 0, 0.000448434, -0.0656908, 2.79061e-07, 2.2724, 16, 0.068547, 0, 0, 0.422134,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.0258e-06, -5.41527e-06, -0.000107617, 0, 0.0945918, 0, 0.00266155, 8.85607e-05, -0.0433648, -2.43333e-07, 0.89549, 16, -0.0474499, 0, 0, 0.534042,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.681953,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0.0625171, 0, 0, -2.28516e-05, 0, -0.0913821, -0.0022017, -0.0106828, 3.33933e-06, 0.032841, 1.92447e-08, -1.39912, -1, -0.0336099, 0, -1, 0.441624,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 20840.1, 0, 0, 0.476932,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1475.92, 1, 0, 0.518261,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.148761);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.609136,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.486794,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 5.96393, 1, 0, 0.55391,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.542056,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.42147,-99) , 
17, 0, 0, 0, 0, 0, 0, 2.48777e-06, 0, -8.77451e-06, 0, 0.0357913, 0, 0.0029227, 8.11691e-06, -0.00647465, -1.88449e-06, 0.294491, 16, -0.00232483, 0, 0, 0.488188,-99) , 
17, 0, 0, 0, 0, 0, 0, -4.90826e-07, 0, -6.16584e-06, 0, -0.0113622, 0, -0.00820693, 8.25534e-06, 0.00985764, 1.96214e-07, -0.114645, 16, 0.00479343, 0, 0, 0.511046,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.642165,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.0990294,-99) , 
17, 0, 0, 0, 0, 0.0519539, 0, -0.000293514, -0.000329725, -0.000309598, -0.000399205, -0.44832, 0, 0.00610979, 0.000234834, 0.121323, 0.000290864, -4.38048, 16, -0.0239177, 0, 0, 0.395975,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8.31306, 0, 0, 0.503577,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.11748);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.57829, 0, 1, 0.690288,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.699623,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.326089,-99) , 
17, 0, 0, 0, 0.000453804, 0, 0.0774164, 2.90058e-06, -5.14097e-06, 0.000353696, 0.0010073, -0.00904746, 0.111549, 0.292733, -0.000441233, -0.383453, -3.26164e-06, -0.657432, 16, 0.0716452, 0, 0, 0.474139,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.53754e-06, -1.22421e-05, 9.98282e-05, 0.000255305, -0.0596674, 0, -0.15495, -6.48542e-05, 0.154523, 2.24043e-06, -0.621582, 16, -0.00695039, 0, 0, 0.583454,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.518335,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.429767,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.41287e-06, 1.02208e-06, -4.83385e-05, 0, 0.0426433, 0, -0.00713685, 2.96833e-05, -0.0178611, -1.41104e-06, 0.455184, 16, -0.0169708, 0, 0, 0.498066,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4.69074, 1, -1, 0.3335,-99) , 
17, 0, 0, 0, 0, 0, 0, -4.45691e-07, 2.41142e-06, -2.90122e-05, 0, -0.0115355, 0, 0.0070697, 2.03964e-05, -0.0124544, -8.63596e-07, -0.0240185, 16, -0.0572735, 0, 0, 0.487229,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 10.4097, 0, 0, 0.499764,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0890889);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.76911,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.632743,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.422216,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3.16889, 1, 0, 0.501396,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.66655e-06, -1.09039e-05, 9.86945e-05, 0.000215712, -0.0419474, 0, -0.145577, -5.88237e-05, 0.143216, 2.09126e-06, -0.471173, 16, 0.0650348, 0, 0, 0.573232,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.502447,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.385978,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.44969e-07, -6.8326e-07, -5.49125e-06, 0, -0.0109934, 0, -0.010846, 3.79816e-06, 0.0152164, 3.52163e-07, -0.123517, 16, -0.0114675, 0, 0, 0.482983,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.25656,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.24255e-06, 1.5413e-06, -2.95219e-06, 0, -0.0426359, 0, 0.0103687, 3.30913e-06, 0.00322058, 1.01045e-07, -0.364219, 16, -0.0541043, 0, 0, 0.474181,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 10.4097, 0, 0, 0.486887,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.157113);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.748217,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.606592,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.405399,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3.81848, 1, 0, 0.508124,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.65087e-06, -1.05412e-05, 9.52306e-05, 0.000209364, -0.0457434, 0, -0.129146, -5.66606e-05, 0.129369, 2.03318e-06, -0.497847, 16, 0.0593976, 0, 0, 0.572222,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.532802,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.387774,-99) , 
17, 0, 0, 0, 0, 0, 0, 8.50747e-06, -1.20337e-05, -5.41329e-05, 0, 0.111269, 0, -0.13341, 2.55145e-05, 0.0819492, -1.47511e-07, 0.969536, 16, -0.0319774, 0, 0, 0.484977,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1784.05, 1, -1, 0.410905,-99) , 
17, 0, 0, 0, 0, 0, 0, -9.45326e-07, 1.67629e-06, 1.36761e-06, 0, -0.0223286, 0, 0.0146737, 7.45082e-07, -0.00783676, -1.19064e-07, -0.174521, 16, -0.00463964, 0, 0, 0.4607,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 10.4097, 0, 0, 0.474879,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.204582);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.726548,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.390541,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 21363.6, 0, 0, 0.638308,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.529788,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.401732,-99) , 
17, 0, 0, 0, 0, 0, 0, -1.46623e-06, 0, 4.87276e-07, 0, 0.00258498, 0, 0.0156791, 4.64639e-06, -0.0294923, -4.09516e-07, 0.184255, 16, -0.0053051, 0, 0, 0.479321,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999999, 0, 0, 0.509268,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.658608,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.393764,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3.99035, 1, 0, 0.555615,-99) , 
NN(
0, 
0, 
17, 0, 0, 0, 0, 0, 0, -3.95636e-06, 0, -3.50634e-05, 0, 0.147962, 0, -0.0833999, 2.25687e-05, -0.0140231, 3.12767e-06, 1.43855, -1, 0.0016763, 0, -1, 0.385772,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 5726.44, 1, 0, 0.438605,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.999986, 0, 0, 0.476567,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0953873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.649239,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.713386,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.479344,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 21643.5, 1, 0, 0.493396,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.80341, 0, -1, 0.414859,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 8.55762, 1, 0, 0.476874,-99) , 
17, 0, 0, 0, 0, 0, 0, -4.12249e-07, 0, 6.09686e-06, 0, -0.0401906, 0, -0.00490036, -9.27491e-06, 0.0233165, 7.64646e-07, -0.411816, 16, 0.0517692, 0, 0, 0.483695,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.070835);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.844065,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.48296,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4.69503, 1, 0, 0.639347,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.509182,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.330318,-99) , 
17, 0, 0, 0, 0, 0, 0, -7.89892e-08, 0, -9.85607e-06, 0, 0.0136148, 0, -0.0208003, 7.19763e-06, 0.014294, -3.37932e-07, 0.128138, 16, 0.0389086, 1, 0, 0.503385,-99) , 
17, 0, 0, 0, 0, 0, 0, -5.28066e-07, 0, 1.09306e-05, 0, -0.0295595, 0, -0.0162738, -8.75136e-06, 0.0283781, 5.91573e-07, -0.308823, 16, 0.0321488, 0, 0, 0.511853,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.603238,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.201005,-99) , 
17, 0, 0, 0, 0, 0.0366851, 0, -0.000277631, -0.000312618, -0.000257795, -0.000415961, -0.521296, 0, 0.0116504, 0.000201984, 0.174032, 0.000276948, -5.19197, 16, -0.00408138, 0, 0, 0.380377,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8.31306, 0, 0, 0.503484,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.152498);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.73846,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.465568,-99) , 
17, 0, 0, 0, 0, 0, 0, 0, -1.06171e-06, 4.88426e-05, -1.89447e-05, 0.129678, 0.0522493, -0.037758, -4.18315e-05, -0.070577, 0, 1.57136, 16, 0.00941523, 0, 0, 0.626551,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.743854,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.473954,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 525.292, 1, 0, 0.509617,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.524696,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.350238,-99) , 
17, 0, 0, 0, 0, 0, 0, 4.14677e-07, 0, -0.000102215, 0, -0.0295504, 0, 0.0525228, 6.62575e-05, -0.0530474, 6.48115e-07, -0.30514, 16, 0.0095516, 0, 0, 0.418435,-99) , 
17, 0, 0, 0, 0, 0, 0, 1.42517e-06, 0, -2.53745e-05, 0, 0.0270392, 0, 0.0102608, 1.99492e-05, -0.0228322, -8.86552e-07, 0.265386, 16, 0.00539408, 1, 0, 0.479452,-99) , 
17, 0, 0, 0, 0, 0, 0, -2.43561e-07, 0, 4.51691e-06, 0, -0.0374933, 0, -0.0104331, -7.18656e-06, 0.0278406, 5.87783e-07, -0.391533, 16, 0.0326427, 0, 0, 0.489182,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.10615);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 8.91241, 1, 1, 0.527602,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.735154,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.334531,-99) , 
17, 0, 0, 0, -0.000223043, 0, 0, 0, 0, -0.000397845, -0.000164189, 0.128531, -0.241676, -0.348448, 0.000247079, 0.507562, 0, 0.761083, 16, 0.126145, 0, 0, 0.429406,-99) , 
17, 0, 0, 0, 0, 0, 0, -8.96534e-07, 0, 2.53152e-05, 0, -0.0306237, 0, -0.0208869, -1.73505e-05, 0.0349123, 7.59154e-07, -0.328813, 16, -0.0204099, 0, 0, 0.515768,-99) , 
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.556714,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.242452,-99) , 
17, 0, 0, 0, 0, 0.0340914, 0, -0.000250941, -0.0002856, -0.000260264, -0.000405276, -0.448597, 0, 0.0195351, 0.000209795, 0.138063, 0.000250832, -4.44816, 16, -0.0172244, 0, 0, 0.40496,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8.31306, 0, 0, 0.508891,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0866045);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.689653,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.485494,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4.65465, 0, 0, 0.596385,-99) , 
NN(
NN(
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.630741,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.475182,-99) , 
17, 0, 0, 0, 0, 0, 0, 4.67931e-06, 0, -3.63226e-05, 0, 0.0274419, 0, 0.00192578, 2.08169e-05, -0.0139388, -1.67138e-06, 0.23681, 16, 0.0485093, 0, 0, 0.488416,-99) , 
NN(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.314751,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 70180.4, 1, 0, 0.482146,-99) , 
17, 0, 0, 0, 0, 0, 0, -3.29688e-07, 0, 9.74131e-06, 0, -0.024374, 0, -0.00704972, -8.3294e-06, 0.0190109, 4.48113e-07, -0.257783, 16, 0.0236626, 0, 0, 0.488477,-99)    );
   return;
};
 
// Clean up
inline void ReadBDTMitFisher::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTMitFisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
