// Class: ReadCutsD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::CutsD
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.04/02       [394242]
Creator        : atrisovi
Date           : Wed Sep 16 15:15:44 2015
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-504.23.4.el6.x86_64 #1 SMP Wed Jun 10 07:47:59 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/a/atrisovi/public
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
    CutRangeMin[4]: "-1.000000e+00"
    CutRangeMin[5]: "-1.000000e+00"
    CutRangeMin[6]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
    CutRangeMax[4]: "-1.000000e+00"
    CutRangeMax[5]: "-1.000000e+00"
    CutRangeMax[6]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FSmart"
    VarProp[4]: "FSmart"
    VarProp[5]: "FSmart"
    VarProp[6]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
D_DIRA_OWNPV                  D_dira                        D_dira                        D_dira                                                          'F'    [0.999899804592,1]
D_IPCHI2_OWNPV                D_ipchi                       D_ipchi                       D_ipchi                                                         'F'    [0.000164741955814,29.2228622437]
piplus_PT                     pi_pt                         pi_pt                         pi_pt                                                           'F'    [300.148986816,9203.84179688]
piplus_P                      pi_p                          pi_p                          pi_p                                                            'F'    [2044.51489258,178502.34375]
D_PT                          D_pt                          D_pt                          D_pt                                                            'F'    [22.1627159119,21832.640625]
D_P                           D_p                           D_p                           D_p                                                             'F'    [10681.8505859,347852.90625]
D_FDCHI2_OWNPV                D_fd                          D_fd                          D_fd                                                            'F'    [8.34407997131,74471.1328125]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCutsD : public IClassifierReader {

 public:

   // constructor
   ReadCutsD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCutsD" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "D_DIRA_OWNPV", "D_IPCHI2_OWNPV", "piplus_PT", "piplus_P", "D_PT", "D_P", "D_FDCHI2_OWNPV" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 44555.6171875;
      fVmax[0] = 44561.4296875;
      fVmin[1] = -1.1252406835556;
      fVmax[1] = 4.82777214050293;
      fVmin[2] = -4.35129117965698;
      fVmax[2] = 9.41275596618652;
      fVmin[3] = -4.89737367630005;
      fVmax[3] = 9.33458805084229;
      fVmin[4] = -2.05848503112793;
      fVmax[4] = 7.99471139907837;
      fVmin[5] = 0.24267441034317;
      fVmax[5] = 9.1126537322998;
      fVmin[6] = -0.135189026594162;
      fVmax[6] = 12.40576171875;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadCutsD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][7][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCutsD"
};
   inline double ReadCutsD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadCutsD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 61780.3698082;
   fDecTF_1[0][0][1] = 0.103429465807;
   fDecTF_1[0][0][2] = 1.31319578742e-05;
   fDecTF_1[0][0][3] = -1.09321846478e-06;
   fDecTF_1[0][0][4] = -3.65344686879e-05;
   fDecTF_1[0][0][5] = -6.54208521784e-06;
   fDecTF_1[0][0][6] = -3.63213366284e-05;
   fDecTF_1[0][1][0] = 0.103429465807;
   fDecTF_1[0][1][1] = 0.227157416589;
   fDecTF_1[0][1][2] = 5.86439340116e-05;
   fDecTF_1[0][1][3] = -2.44662863917e-06;
   fDecTF_1[0][1][4] = -1.53818718034e-05;
   fDecTF_1[0][1][5] = -3.25545205135e-08;
   fDecTF_1[0][1][6] = -1.12471261637e-05;
   fDecTF_1[0][2][0] = 1.31319578742e-05;
   fDecTF_1[0][2][1] = 5.86439340116e-05;
   fDecTF_1[0][2][2] = 0.00178776421951;
   fDecTF_1[0][2][3] = -7.34463947983e-05;
   fDecTF_1[0][2][4] = -0.0004318744655;
   fDecTF_1[0][2][5] = 2.19710138397e-05;
   fDecTF_1[0][2][6] = -6.5732202992e-06;
   fDecTF_1[0][3][0] = -1.09321846478e-06;
   fDecTF_1[0][3][1] = -2.44662863917e-06;
   fDecTF_1[0][3][2] = -7.34463947983e-05;
   fDecTF_1[0][3][3] = 7.21262171514e-05;
   fDecTF_1[0][3][4] = 1.86453455016e-05;
   fDecTF_1[0][3][5] = -1.84914649102e-05;
   fDecTF_1[0][3][6] = 1.52923008341e-06;
   fDecTF_1[0][4][0] = -3.65344686879e-05;
   fDecTF_1[0][4][1] = -1.53818718034e-05;
   fDecTF_1[0][4][2] = -0.0004318744655;
   fDecTF_1[0][4][3] = 1.86453455016e-05;
   fDecTF_1[0][4][4] = 0.000565165438337;
   fDecTF_1[0][4][5] = -1.76160670881e-05;
   fDecTF_1[0][4][6] = -3.37445405644e-05;
   fDecTF_1[0][5][0] = -6.54208521784e-06;
   fDecTF_1[0][5][1] = -3.25545205135e-08;
   fDecTF_1[0][5][2] = 2.19710138397e-05;
   fDecTF_1[0][5][3] = -1.84914649102e-05;
   fDecTF_1[0][5][4] = -1.76160670881e-05;
   fDecTF_1[0][5][5] = 2.83610053118e-05;
   fDecTF_1[0][5][6] = -4.25025835923e-07;
   fDecTF_1[0][6][0] = -3.63213366284e-05;
   fDecTF_1[0][6][1] = -1.12471261637e-05;
   fDecTF_1[0][6][2] = -6.5732202992e-06;
   fDecTF_1[0][6][3] = 1.52923008341e-06;
   fDecTF_1[0][6][4] = -3.37445405644e-05;
   fDecTF_1[0][6][5] = -4.25025835923e-07;
   fDecTF_1[0][6][6] = 0.000166576754169;
   fDecTF_1[1][0][0] = 40221.7526929;
   fDecTF_1[1][0][1] = 0.0507108763641;
   fDecTF_1[1][0][2] = -1.55672902947e-05;
   fDecTF_1[1][0][3] = 5.41663359145e-07;
   fDecTF_1[1][0][4] = -4.4158933448e-05;
   fDecTF_1[1][0][5] = -8.69158411129e-06;
   fDecTF_1[1][0][6] = -6.04733475348e-05;
   fDecTF_1[1][1][0] = 0.0507108763641;
   fDecTF_1[1][1][1] = 0.153449949656;
   fDecTF_1[1][1][2] = -2.13923330777e-05;
   fDecTF_1[1][1][3] = 3.38904504029e-06;
   fDecTF_1[1][1][4] = -4.46566530316e-05;
   fDecTF_1[1][1][5] = -5.26479794233e-06;
   fDecTF_1[1][1][6] = -3.2324889881e-05;
   fDecTF_1[1][2][0] = -1.55672902947e-05;
   fDecTF_1[1][2][1] = -2.13923330777e-05;
   fDecTF_1[1][2][2] = 0.00184903927143;
   fDecTF_1[1][2][3] = -8.8152274869e-05;
   fDecTF_1[1][2][4] = -0.000372880718504;
   fDecTF_1[1][2][5] = 2.28290764051e-05;
   fDecTF_1[1][2][6] = -4.10079631009e-06;
   fDecTF_1[1][3][0] = 5.41663359146e-07;
   fDecTF_1[1][3][1] = 3.38904504029e-06;
   fDecTF_1[1][3][2] = -8.8152274869e-05;
   fDecTF_1[1][3][3] = 7.84425508812e-05;
   fDecTF_1[1][3][4] = 2.33979773536e-05;
   fDecTF_1[1][3][5] = -1.55184411281e-05;
   fDecTF_1[1][3][6] = 1.98520314756e-06;
   fDecTF_1[1][4][0] = -4.4158933448e-05;
   fDecTF_1[1][4][1] = -4.46566530316e-05;
   fDecTF_1[1][4][2] = -0.000372880718504;
   fDecTF_1[1][4][3] = 2.33979773536e-05;
   fDecTF_1[1][4][4] = 0.000537828662608;
   fDecTF_1[1][4][5] = -2.36364453958e-05;
   fDecTF_1[1][4][6] = 1.19965269792e-05;
   fDecTF_1[1][5][0] = -8.69158411129e-06;
   fDecTF_1[1][5][1] = -5.26479794233e-06;
   fDecTF_1[1][5][2] = 2.28290764051e-05;
   fDecTF_1[1][5][3] = -1.55184411281e-05;
   fDecTF_1[1][5][4] = -2.36364453958e-05;
   fDecTF_1[1][5][5] = 2.81422297571e-05;
   fDecTF_1[1][5][6] = 1.64313754582e-06;
   fDecTF_1[1][6][0] = -6.04733475348e-05;
   fDecTF_1[1][6][1] = -3.2324889881e-05;
   fDecTF_1[1][6][2] = -4.10079631009e-06;
   fDecTF_1[1][6][3] = 1.98520314756e-06;
   fDecTF_1[1][6][4] = 1.19965269792e-05;
   fDecTF_1[1][6][5] = 1.64313754582e-06;
   fDecTF_1[1][6][6] = 0.000171528723079;
   fDecTF_1[2][0][0] = 44560.6566901;
   fDecTF_1[2][0][1] = 0.0735255410328;
   fDecTF_1[2][0][2] = -3.0576114256e-05;
   fDecTF_1[2][0][3] = 1.209783836e-06;
   fDecTF_1[2][0][4] = -3.57587837644e-05;
   fDecTF_1[2][0][5] = -8.09189021382e-06;
   fDecTF_1[2][0][6] = -4.78422091556e-05;
   fDecTF_1[2][1][0] = 0.0735255410328;
   fDecTF_1[2][1][1] = 0.168264525747;
   fDecTF_1[2][1][2] = 5.75259296735e-05;
   fDecTF_1[2][1][3] = 1.33825820624e-06;
   fDecTF_1[2][1][4] = -3.41239643863e-05;
   fDecTF_1[2][1][5] = -2.42386135617e-06;
   fDecTF_1[2][1][6] = -1.40070088916e-05;
   fDecTF_1[2][2][0] = -3.0576114256e-05;
   fDecTF_1[2][2][1] = 5.75259296735e-05;
   fDecTF_1[2][2][2] = 0.00179657431762;
   fDecTF_1[2][2][3] = -7.96823679054e-05;
   fDecTF_1[2][2][4] = -0.000398898784127;
   fDecTF_1[2][2][5] = 2.24463920486e-05;
   fDecTF_1[2][2][6] = -8.35502639618e-06;
   fDecTF_1[2][3][0] = 1.209783836e-06;
   fDecTF_1[2][3][1] = 1.33825820624e-06;
   fDecTF_1[2][3][2] = -7.96823679054e-05;
   fDecTF_1[2][3][3] = 7.43557268674e-05;
   fDecTF_1[2][3][4] = 2.14882078954e-05;
   fDecTF_1[2][3][5] = -1.7111346962e-05;
   fDecTF_1[2][3][6] = 9.41129123665e-07;
   fDecTF_1[2][4][0] = -3.57587837644e-05;
   fDecTF_1[2][4][1] = -3.41239643863e-05;
   fDecTF_1[2][4][2] = -0.000398898784127;
   fDecTF_1[2][4][3] = 2.14882078954e-05;
   fDecTF_1[2][4][4] = 0.000538620937907;
   fDecTF_1[2][4][5] = -2.07581984461e-05;
   fDecTF_1[2][4][6] = -1.00921206275e-05;
   fDecTF_1[2][5][0] = -8.09189021382e-06;
   fDecTF_1[2][5][1] = -2.42386135617e-06;
   fDecTF_1[2][5][2] = 2.24463920486e-05;
   fDecTF_1[2][5][3] = -1.7111346962e-05;
   fDecTF_1[2][5][4] = -2.07581984461e-05;
   fDecTF_1[2][5][5] = 2.81142998414e-05;
   fDecTF_1[2][5][6] = 6.86055562128e-07;
   fDecTF_1[2][6][0] = -4.78422091556e-05;
   fDecTF_1[2][6][1] = -1.40070088916e-05;
   fDecTF_1[2][6][2] = -8.35502639618e-06;
   fDecTF_1[2][6][3] = 9.41129123665e-07;
   fDecTF_1[2][6][4] = -1.00921206275e-05;
   fDecTF_1[2][6][5] = 6.86055562128e-07;
   fDecTF_1[2][6][6] = 0.000166433549367;
}

//_______________________________________________________________________
inline void ReadCutsD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
   } 

   std::vector<double> tv;
   for (int i=0; i<7;i++) {
      double v = 0;
      for (int j=0; j<7; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<7;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadCutsD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadCutsD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
